# Generated by Django 4.0 on 2021-12-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='created_at',
        ),
        migrations.AddField(
            model_name='basket',
            name='shopping_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
